name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'apps/**'
      - 'packages/**'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      environment: 'ci'
